name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
    ROOT_DIR: ../../
    TEST_PATH: ${{ env.ROOT_DIR }}/tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    # Run flake8 to check code format
    - name: Run flake8 linter
      run: poetry run flake8 .

    - name: Unit Testing
      run: |
          cd ${{ env.TEST_PATH }}
          poetry run pytest